[package]
name = "rust-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
iced = { version = "0.14.0", features = ["image", "advanced", "tokio"]}
image = "0.25.9"
rfd = "0.17.2"
rig-core = "0.31.0"
thiserror = "2.0.18"
tokio = "1.49.0"
